export const enum Urls {
  USERS = 'users',
  USER_FORM = 'user_form',
  BRANCHES = 'branches',
  BRANCH_FORM = 'branch_form',
  ENTITIES = 'entities',
  ENTITY_FORM = 'entity_form',
  PROFILE_EDIT = 'edit',
  LOAN_FORM = 'loan_form',
  LOAN_PRODUCTS = 'loan_products',
  LOAN_PRODUCT_FORM = 'loan_products_form',
  DASHBOARD = 'dashboard',
  AUDITING = 'auditing',
  CUSTOMER_FORM = 'customer_form',
  CUSTOMERS = 'customers',
  REPORTS = 'reports',
  LOGGED_USERS = 'logged',
  HOME = 'home',
}
